# -*- coding: utf-8 -*-
"""Catalogo_Peliculas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CivATOjD047hO7Mf2gX1trZu4Izy8Whs
"""

import os

class Pelicula:
    def __init__(self, titulo):
        self.titulo = titulo

class CatalogoPeliculas:
    def __init__(self, nombre):
        self.nombre = nombre
        self.archivo = nombre + ".txt"
        if not os.path.exists(self.archivo):
            with open(self.archivo, 'w') as f:
                pass

    def agregar_pelicula(self, pelicula):
        with open(self.archivo, 'a') as f:
            f.write(pelicula.titulo + '\n')

    def listar_peliculas(self):
        with open(self.archivo, 'r') as f:
            peliculas = f.readlines()
            if peliculas:
                print("\nPelículas en el catálogo:")
                for pelicula in peliculas:
                    print(pelicula.strip())
            else:
                print("No hay películas en el catálogo.")

    def eliminar_catalogo(self):
        if os.path.exists(self.archivo):
            os.remove(self.archivo)
            print("Catálogo de películas eliminado.")
        else:
            print("El catálogo de películas no existe.")

def mostrar_menu():
    print("\n*** Menú ***")
    print("1. Agregar Película")
    print("2. Listar Películas")
    print("3. Eliminar Catálogo de Películas")
    print("4. Salir")

if __name__ == "__main__":
    print("¡Bienvenido al administrador de películas!")

    nombre_catalogo = input("Por favor, ingresa el nombre de tu catálogo de películas: ")
    catalogo = CatalogoPeliculas(nombre_catalogo)

    while True:
        mostrar_menu()
        opcion = input("Selecciona una opción: ")

        if opcion == "1":
            titulo_pelicula = input("Ingresa el título de la película que deseas agregar: ")
            pelicula = Pelicula(titulo_pelicula)
            catalogo.agregar_pelicula(pelicula)
        elif opcion == "2":
            catalogo.listar_peliculas()
        elif opcion == "3":
            confirmacion = input("¿Estás seguro que deseas eliminar el catálogo de películas? (s/n): ")
            if confirmacion.lower() == "s":
                catalogo.eliminar_catalogo()
        elif opcion == "4":
            print("¡Gracias por usar el administrador de películas!")
            break
        else:
            print("Opción no válida. Por favor, selecciona una opción válida.")